version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - main
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    restart: always
  mongo:
    image: mongo
    restart: always
    networks:
      - main
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
networks:
  main:
    driver: bridge
